export class Employee {
    $key : string;  // used to Store unique key automatically generated by firebase db when insert new record
    name : string;
    position : string;
    office : string;
    salary : number;
}
